### ISSUE TITLE
Line break in warning messages would be nice

### ISSUE THREAD

**Issue by mifek** [BalintKomjati/bmarketing#10]
https://github.com/BalintKomjati/bmarketing/blob/1778be4c1b6bf7cb1290a6b2659fcbc7c29f0acd/R/clean.R#L25

**Comment by zoltanszebenyi** [comment]
should be nicer output now:

> cleaned_data <- clean(bmarketing, "X")
Warning messages:
1: In clean(bmarketing, "X") : Explanatory variables contain NA values
2: In clean(bmarketing, "X") :
  The following columns are removed:  HOUSING, POUTCOME, MONTH
