### ISSUE TITLE
only one function is available calcPerformance is avalable

### ISSUE THREAD

**Issue by LarisaYanceva** [BalintKomjati/bmarketing#3]

**Comment by zoltanszebenyi** [comment]
Hi, do you see the clean.R and Transform.R functions?

**Comment by TiborSzabo42** [comment]
We decided not to create unnecessary functions which only purpose to call another existing ones. For example function rpart is already there, and more flexible (e.g. you can specifiy your own model formula), while with writting a function around it you lose functionalities. So we skipped implementing functions for the followings:

* Model: Create a new model based on data = rpart
* Model-Plot: Plot model, e.g. decision tree = rpart.plot
* Model-Predict = predict function

**Comment by BalintKomjati** [comment]
With the latest commit ec5fbf5 functions within the package should now appear in the default namespace.
