### ISSUE TITLE
Clean function does not show Error. 

### ISSUE THREAD

**Issue by lyrabe** [BalintKomjati/bmarketing#5]
The clean function is supposed to show an error if the target variable has NA values, but it did not do it.

**Comment by zoltanszebenyi** [comment]
Hi, could you show me your test case?

It works for me:
> test_data <- as.data.frame(cbind(c(1,2,3), c("a","b","c"), c(5,NA,7)))
> colnames(test_data) <- c("ev1","ev2","tv") #naming columns: ev1 = explanatory var.1, etc; tv = target var
> clean(test_data, "tv")
Error in clean(test_data, "tv") : The target variabe t contais NA values

**Comment by zoltanszebenyi** [comment]
it should work now, test:

> cleaned_data <- clean(bmarketing, "DEFAULT")
Error in clean(bmarketing, "DEFAULT") : 
  The target variabe DEFAULT contais NA values
