### ISSUE TITLE
Target variable is not checkt for NAs

### ISSUE THREAD

**Issue by mifek** [BalintKomjati/bmarketing#8]
https://github.com/BalintKomjati/bmarketing/blob/1778be4c1b6bf7cb1290a6b2659fcbc7c29f0acd/R/clean.R#L19

This line checks a column 't' for NAs and not the one in the parameter provided by the user

**Comment by zoltanszebenyi** [comment]
should be fixed now, test:

> cleaned_data <- clean(bmarketing, "DEFAULT")
Error in clean(bmarketing, "DEFAULT") : 
  The target variabe DEFAULT contais NA values
